services:
  database:
    image: postgres:15
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_SSLMODE: disable
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./migration/000001_init.up.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - "5432"

  wallet:
    build: .
    container_name: wallet
    restart: always
    environment:
      - ADDRESS=${ADDRESS}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - database
    ports:
      - "${ADDRESS}:${ADDRESS}"